# Generated by Django 4.0.4 on 2022-06-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appo_Number', models.IntegerField()),
                ('Appo_Type', models.CharField(max_length=30)),
                ('Appo_Description', models.CharField(max_length=120)),
                ('Appo_Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=120, verbose_name='first name')),
                ('MiddleName', models.CharField(max_length=120, verbose_name='middle name')),
                ('Lastname', models.CharField(max_length=120, verbose_name='last name')),
                ('Telephone', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=20, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Speciality', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=120, verbose_name='first name')),
                ('MiddleName', models.CharField(max_length=120, verbose_name='middle name')),
                ('Lastname', models.CharField(max_length=120, verbose_name='last name')),
                ('Telephone', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=20, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Appointments_Available', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShireDental.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShireDental.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShireDental.doctor'),
        ),
    ]
